# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

variables:
  POSTGRES: postgres
  SVELTE: svelte
  SPRINGBOOT: springboot

  IMAGE_TAG: latest
  ## for gitlab image registry:
  REPO_PATH: gitlab.uliege.be:5050/speam/2024-2025/team3/mdtools
  REGISTRY_HOST: gitlab.uliege.be:5050
  # GITLAB_REGISTRY_USER and GITLAB_REGISTRY_TOKEN are defined in the secret store
  PUSH_USER: $GITLAB_REGISTRY_USER
  PUSH_TOKEN: $GITLAB_REGISTRY_TOKEN
   
stages: # List of stages for grouping and sequencing jobs, and their order of execution
  - prepare
  - test
  - package
  - deploy

postgres_init:
  stage: prepare
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - changes:
        paths: 
          - Dockerfile-postgres
          - $CI_CONFIG_PATH
  tags:
    - openshift 
    - docker
  image: docker:20.10.16
  variables:
    REPO_TAG: ${REPO_PATH}postgres:${IMAGE_TAG}
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
    - docker:20.10.16-dind
  before_script:
    - sleep 10 && docker info
    - echo $PUSH_TOKEN | docker login $REGISTRY_HOST -u $PUSH_USER --password-stdin
  script:
    - echo $REPO_TAG
    - docker build --network host -t $REPO_TAG -f Dockerfile-postgres .
    - docker push $REPO_TAG
