services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: "postgres"
    environment:
<<<<<<< HEAD
      POSTGRES_USER: team03
      POSTGRES_PASSWORD: mdtools
      PGDATA: /home/postgres_user/data
=======
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
>>>>>>> a51169ad5350c6850f5a49f9b8941dd5b356dac2
    volumes:
      #- pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  svelte:
    build:
      context: .            # Path to your Dockerfile and frontend directory
      dockerfile: Dockerfile-svelte
    container_name: "svelte"
    ports:
      - "3000:3000"         # Maps port 3000 on the host to port 3000 in the container
    environment:
      NODE_ENV: development  # Ensures the app runs in dev mode, use production for production
    restart: unless-stopped # Automatically restarts the container unless manually stopped

<<<<<<< HEAD
#   springboot:
#     build:
#       context: .
#       dockerfile: Dockerfile-springboot
#     container_name: "springboot"
#     volumes:
#       - ./springboot:/home/springboot_user/springboot
#     ports:
#       - "8080:8080"
#     restart: unless-stopped
=======
  springboot:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    container_name: "springboot"
    volumes:
      - ./backend:/app/backend  # Mount the backend directory for live reload
    ports:
      - "8080:8080"  # Expose the Spring Boot application port
    environment:
      SPRING_PROFILES_ACTIVE: "dev"  # Activate the development profile
      spring.datasource.url: "jdbc:postgresql://postgres:5432/postgres"
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.datasource.driver.class.name: "org.postgresql.Driver"
>>>>>>> a51169ad5350c6850f5a49f9b8941dd5b356dac2

volumes:
  pgdata:
    driver: local