services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: "postgres"
    environment:
      POSTGRES_USER: mdtools
      POSTGRES_PASSWORD: team03
    volumes:
      - pgdata:/home/postgres_user/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
    driver: local