services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      #- pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_PASSWORD}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s 

  svelte:
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    container_name: "svelte"
    volumes:
      - ./frontend/src:/app/src  # Mount the src directory for live reload
      - ./frontend/static:/app/static # Mount the static directory for live reload
    ports:
      - "3000:3000"         # Maps port 3000 on the host to port 3000 in the container
    environment:
      - NODE_ENV=development  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s


  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: "springboot"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend  # Mount the backend directory for live reload
    ports:
      - "8080:8080"  # Expose the Spring Boot application port
    environment:
      SPRING_PROFILES_ACTIVE: "dev"  # Activate the development profile
      spring.datasource.url: "jdbc:postgresql://postgres:5432/team03"
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.datasource.driver.class.name: "org.postgresql.Driver"

volumes:
  pgdata:
    driver: local