services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      #- pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d team03"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s 

  svelte:
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    container_name: "svelte"
    volumes:
      - ./frontend/src:/app/src  # Mount the src directory for live reload
      - ./frontend/static:/app/static # Mount the static directory for live reload
    ports:
      - "3000:3000"         # Maps port 3000 on the host to port 3000 in the container
    environment:
      - NODE_ENV=development  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s


  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: "springboot"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/src  # Mount the backend directory for live reload
      - ./backend/src/main/resources/pictures:/app/pictures  # Mount the pictures directory
    ports:
      - "8080:8080"  # Expose the Spring Boot application port
volumes:
  pgdata:
    driver: local