services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      - pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      # - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d team03"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s
    networks:
      - mdtools

  svelte:
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    container_name: "svelte"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src  # Mount the src directory for live reload
      - ./frontend/static:/app/static # Mount the static directory for live reload
    ports:
      - "3000:3000"         # Maps port 3000 on the host to port 3000 in the container
    depends_on:
      - springboot
    environment:
      - NODE_ENV=development  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - mdtools


  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: "springboot"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/src  # Mount the backend directory for live reload
      - ./backend/src/main/resources/pictures:/app/pictures  # Mount the pictures directory
      - pictures:/app/pictures
    ports:
      - "8080:8080"  # Expose the Spring Boot application port
    networks:
      - mdtools


  dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    container_name: dex
    restart: unless-stopped
    ports:
      - "5556:5556"  # DeX runs on port 5556
    volumes:
      - ./dex/dex-config.yaml:/etc/dex/config.yaml
      - ./dex/dex-data:/data
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    networks:
      - mdtools

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      mdtools:
        aliases:
          - dex.localhost.direct

volumes:
  pgdata:
    driver: local
  pictures:
    driver: local

networks:
  mdtools:
    driver: bridge