services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: "postgres"
    environment:
      POSTGRES_USER: team03
      POSTGRES_PASSWORD: mdtools
    volumes:
      - pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      # pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  svelte:
    build:
      context: .
      dockerfile: Dockerfile-svelte
    container_name: "svelte"
    volumes:
      - ./svelte:/home/svelte_user/svelte
    ports:
      - "5000:5000"
    restart: unless-stopped

  springboot:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    container_name: "springboot"
    volumes:
      - ./springboot:/home/springboot_user/springboot
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
    driver: local