services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      - pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      # - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d team03"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s
    networks:
      - mdtools

  svelte:
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    container_name: "svelte"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src  # Mount the src directory for live reload
      - ./frontend/static:/app/static # Mount the static directory for live reload
    ports:
      - "3000:3000"         # Maps port 3000 on the host to port 3000 in the container
    depends_on:
      - springboot
    environment:
      - NODE_ENV=development  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - mdtools


  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: "springboot"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    volumes:
      - ./backend:/app/src  # Mount the backend directory for live reload
      - ./backend/src/main/resources/pictures:/app/pictures  # Mount the pictures directory
      - pictures:/app/pictures
    ports:
      - "8080:8080"  # Expose the Spring Boot application port
    networks:
      - mdtools


  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      mdtools:
        aliases:
          - keycloak.localhost.direct

  keycloak-db:  
    image: postgres:15
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - kc_data:/var/lib/postgresql/data
    networks:
      - mdtools

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./Keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s

    networks:
      mdtools:
        aliases:
          - keycloak.localhost.direct


volumes:
  pgdata:
    driver: local
  pictures:
    driver: local
  kc_data:
    driver: local

networks:
  mdtools:
    driver: bridge