apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.prod.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  tags:
    - importPolicy:
        scheduled: true
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.prod.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres
    spec:
      initContainers:
      - name: set-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /mnt/data"]
        volumeMounts:
        - name: postgres-data
          mountPath: /mnt/data
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: mdtools
            - name: POSTGRES_USER
              value: team03
          image: gitlab.uliege.be:5050/speam/2024-2025/team3/mdtools/postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /home/postgres_user/
              name: pgdata
      restartPolicy: Always
      imagePullSecrets:
        - name: mdtools-gitlab-registry-deploytoken
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
