services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: "postgres"
    environment:

      POSTGRES_USER: team03
      POSTGRES_PASSWORD: mdtools
    volumes:
      #- pgdata:/home/postgres_user/data
      # pgdata is a named volume, which is a persistent volume
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  svelte:
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    container_name: "svelte"
    ports:
      - "3000:3000"         # Maps port 3000 on the host to port 3000 in the container
    environment:
      NODE_ENV: production  
    restart: unless-stopped

  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: "springboot"
    ports:
      - "8080:8080"  # Expose the Spring Boot application port
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/postgres"
      spring.datasource.username: team03
      spring.datasource.password: mdtools
      spring.datasource.driver.class.name: "org.postgresql.Driver"

volumes:
  pgdata:
    driver: local